### ISSUE TITLE
You need to enable JavaScript to run this app, While deploying the react build

### ISSUE THREAD

**Issue by abinth11** [phoenixcoded/able-pro-free-admin-dashboard-template#33]
I’m encountering an issue while deploying the React build statically. I can successfully deploy the build with the aid of a server, but when attempting to deploy it statically, nothing loads. Instead, a message appears inside a <noscript> tag: “You need to enable JavaScript to run this app.” Despite trying several solutions found online, none have resolved the issue. I’ve even verified that it’s not a code-related issue by attempting to deploy the template itself without any modifications. If anyone has insights or solutions, your help would be greatly appreciated. Thank you.

**Comment by phoenixcoded** [comment]
You need run following command to view prod build locally.
**`"preview": "vite preview"`** // locally preview production build
